# Site Settings
title:               Jakub Wi≈õniewski
tagline:             Blog
description:
baseurl:            #"/Lagrange"
url:                #"https://jakub-wisniewski.github.io"
github:
  url:               "https://jakub-wisniewski.github.io/Lagrange"
author:
  name:              "Paul Le"
  email:             "l.nguyen.paul@gmail.com"
  twitter:           "paululele"
  instagram:         "paululele"
  github:            "lenpaul"
  facebook:          "Le.Paul.94"
  linkedin:          "lenpaul"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
